### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by griyamobilkita** [GiulioRossetti/AGraphlets#1]
-------------------------------------
            {AGraphlet}
   Approximate Graphlet Extraction
-------------------------------------
Author: rossetti
Email:  giulio.rossetti@gmail.com
------------------------------------
Calculating NC score...
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\graf\AGraphlets.py", line 230, in <module>
    ag.execute(min_pattern_size=args.min_graphlet_size, max_pattern_size=args.max_graphlet_size)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\graf\AGraphlets.py", line 183, in execute
    self.__backbone()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\graf\AGraphlets.py", line 53, in __backbone
    os.remove("res/simplified_nc.csv")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'res/simplified_nc.csv'

I got this error message. Any suggestion? 

Thank you

**Comment by GiulioRossetti** [comment]
It seems that the file simplified_nc.csv has been already opened by some other program therefore it cannot be deleted.
